# Generated by Django 4.2.30 on 2026-08-03 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('earned_credits', models.IntegerField()),
                ('record_file', models.FileField(blank=True, null=True, upload_to='academic_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-semester'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('verify', 'Verify'), ('reject', 'Reject')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sri Krishna Institute of Technology', max_length=300)),
                ('short_name', models.CharField(default='SKIT', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('principal_email', models.EmailField(blank=True, max_length=254)),
                ('placement_officer_name', models.CharField(blank=True, max_length=200)),
                ('placement_officer_email', models.EmailField(blank=True, max_length=254)),
                ('placement_officer_phone', models.CharField(blank=True, max_length=20)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'College Info',
            },
        ),
        migrations.CreateModel(
            name='DashboardStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('student_applications', 'Student Applications'), ('student_interviews', 'Student Interviews'), ('recruiter_jobs', 'Recruiter Jobs'), ('recruiter_applications', 'Recruiter Applications'), ('admin_total_students', 'Admin Total Students'), ('admin_total_jobs', 'Admin Total Jobs'), ('admin_placements', 'Admin Placements')], max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hod_name', models.CharField(blank=True, max_length=200)),
                ('hod_email', models.EmailField(blank=True, max_length=254)),
                ('total_seats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('office_hours', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application_received', 'Application Received'), ('application_status', 'Application Status Update'), ('interview_scheduled', 'Interview Scheduled'), ('offer_received', 'Offer Received'), ('job_posted', 'Job Posted'), ('placement_drive', 'Placement Drive'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_letter_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('offer_letter_url', models.URLField(blank=True)),
                ('joining_date', models.DateField()),
                ('validity_end_date', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='generated', max_length=20)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('estimated_positions', models.IntegerField(default=1)),
                ('target_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('placed_students', models.IntegerField(default=0)),
                ('highest_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lowest_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_offers', models.IntegerField(default=0)),
                ('companies_visited', models.IntegerField(default=0)),
                ('report_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('managerial', 'Managerial'), ('group', 'Group Discussion')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-applied_at'], name='core_applic_applica_9d77e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='core_applic_job_id_1973bc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-applied_at'], name='core_applic_status_f64be4_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_date'], name='core_interv_status_8cb6b6_idx'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='core.company'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_recruiters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementreport',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='placementreport',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_reports', to='core.collegeinfo'),
        ),
        migrations.AddField(
            model_name='placementreport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='core.collegeinfo'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='core.company'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placement_drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='target_departments',
            field=models.ManyToManyField(related_name='placement_drives', to='core.department'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='core.application'),
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.company'),
        ),
        migrations.AddField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.job'),
        ),
        migrations.AddField(
            model_name='offer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='core.department'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.collegeinfo'),
        ),
        migrations.AddField(
            model_name='dashboardstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.collegeinfo'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='placementreport',
            unique_together={('college', 'department', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('college', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardstatistic',
            unique_together={('user', 'stat_type')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', '-created_at'], name='core_activi_entity__e74002_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('college', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'semester', 'academic_year')},
        ),
    ]
