# Generated by Django 3.2.25 on 2026-08-02 08:45

import core.mongo_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=core.mongo_storage.GridFSStorage(), upload_to='resumes/'),
        ),
    ]
